# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.allele_matrix_details import AlleleMatrixDetails  # noqa: F401,E501
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi import util


class AlleleMatrixDetailsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: List[AlleleMatrixDetails]=None):  # noqa: E501
        """AlleleMatrixDetailsResponse - a model defined in Swagger

        :param metadata: The metadata of this AlleleMatrixDetailsResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this AlleleMatrixDetailsResponse.  # noqa: E501
        :type result: List[AlleleMatrixDetails]
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': List[AlleleMatrixDetails]
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'AlleleMatrixDetailsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The alleleMatrixDetailsResponse of this AlleleMatrixDetailsResponse.  # noqa: E501
        :rtype: AlleleMatrixDetailsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this AlleleMatrixDetailsResponse.


        :return: The metadata of this AlleleMatrixDetailsResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this AlleleMatrixDetailsResponse.


        :param metadata: The metadata of this AlleleMatrixDetailsResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> List[AlleleMatrixDetails]:
        """Gets the result of this AlleleMatrixDetailsResponse.


        :return: The result of this AlleleMatrixDetailsResponse.
        :rtype: List[AlleleMatrixDetails]
        """
        return self._result

    @result.setter
    def result(self, result: List[AlleleMatrixDetails]):
        """Sets the result of this AlleleMatrixDetailsResponse.


        :param result: The result of this AlleleMatrixDetailsResponse.
        :type result: List[AlleleMatrixDetails]
        """

        self._result = result
