# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi import util


class AlleleMatrixDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, description: str=None, last_updated: datetime=None, matrix_db_id: str=None, matrix_name: str=None, name: str=None, study_db_id: str=None):  # noqa: E501
        """AlleleMatrixDetails - a model defined in Swagger

        :param description: The description of this AlleleMatrixDetails.  # noqa: E501
        :type description: str
        :param last_updated: The last_updated of this AlleleMatrixDetails.  # noqa: E501
        :type last_updated: datetime
        :param matrix_db_id: The matrix_db_id of this AlleleMatrixDetails.  # noqa: E501
        :type matrix_db_id: str
        :param matrix_name: The matrix_name of this AlleleMatrixDetails.  # noqa: E501
        :type matrix_name: str
        :param name: The name of this AlleleMatrixDetails.  # noqa: E501
        :type name: str
        :param study_db_id: The study_db_id of this AlleleMatrixDetails.  # noqa: E501
        :type study_db_id: str
        """
        self.swagger_types = {
            'description': str,
            'last_updated': datetime,
            'matrix_db_id': str,
            'matrix_name': str,
            'name': str,
            'study_db_id': str
        }

        self.attribute_map = {
            'description': 'description',
            'last_updated': 'lastUpdated',
            'matrix_db_id': 'matrixDbId',
            'matrix_name': 'matrixName',
            'name': 'name',
            'study_db_id': 'studyDbId'
        }

        self._description = description
        self._last_updated = last_updated
        self._matrix_db_id = matrix_db_id
        self._matrix_name = matrix_name
        self._name = name
        self._study_db_id = study_db_id

    @classmethod
    def from_dict(cls, dikt) -> 'AlleleMatrixDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The alleleMatrixDetails of this AlleleMatrixDetails.  # noqa: E501
        :rtype: AlleleMatrixDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """Gets the description of this AlleleMatrixDetails.

        How the matrix was generated  # noqa: E501

        :return: The description of this AlleleMatrixDetails.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this AlleleMatrixDetails.

        How the matrix was generated  # noqa: E501

        :param description: The description of this AlleleMatrixDetails.
        :type description: str
        """

        self._description = description

    @property
    def last_updated(self) -> datetime:
        """Gets the last_updated of this AlleleMatrixDetails.

        A date format  # noqa: E501

        :return: The last_updated of this AlleleMatrixDetails.
        :rtype: datetime
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated: datetime):
        """Sets the last_updated of this AlleleMatrixDetails.

        A date format  # noqa: E501

        :param last_updated: The last_updated of this AlleleMatrixDetails.
        :type last_updated: datetime
        """

        self._last_updated = last_updated

    @property
    def matrix_db_id(self) -> str:
        """Gets the matrix_db_id of this AlleleMatrixDetails.

        ID of the matrix  # noqa: E501

        :return: The matrix_db_id of this AlleleMatrixDetails.
        :rtype: str
        """
        return self._matrix_db_id

    @matrix_db_id.setter
    def matrix_db_id(self, matrix_db_id: str):
        """Sets the matrix_db_id of this AlleleMatrixDetails.

        ID of the matrix  # noqa: E501

        :param matrix_db_id: The matrix_db_id of this AlleleMatrixDetails.
        :type matrix_db_id: str
        """

        self._matrix_db_id = matrix_db_id

    @property
    def matrix_name(self) -> str:
        """Gets the matrix_name of this AlleleMatrixDetails.

        Name of the matrix  # noqa: E501

        :return: The matrix_name of this AlleleMatrixDetails.
        :rtype: str
        """
        return self._matrix_name

    @matrix_name.setter
    def matrix_name(self, matrix_name: str):
        """Sets the matrix_name of this AlleleMatrixDetails.

        Name of the matrix  # noqa: E501

        :param matrix_name: The matrix_name of this AlleleMatrixDetails.
        :type matrix_name: str
        """

        self._matrix_name = matrix_name

    @property
    def name(self) -> str:
        """Gets the name of this AlleleMatrixDetails.

        DEPRECATED in v1.3 - Use \"matrixName\"  # noqa: E501

        :return: The name of this AlleleMatrixDetails.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AlleleMatrixDetails.

        DEPRECATED in v1.3 - Use \"matrixName\"  # noqa: E501

        :param name: The name of this AlleleMatrixDetails.
        :type name: str
        """

        self._name = name

    @property
    def study_db_id(self) -> str:
        """Gets the study_db_id of this AlleleMatrixDetails.

        Link to the study where the matrix was produced  # noqa: E501

        :return: The study_db_id of this AlleleMatrixDetails.
        :rtype: str
        """
        return self._study_db_id

    @study_db_id.setter
    def study_db_id(self, study_db_id: str):
        """Sets the study_db_id of this AlleleMatrixDetails.

        Link to the study where the matrix was produced  # noqa: E501

        :param study_db_id: The study_db_id of this AlleleMatrixDetails.
        :type study_db_id: str
        """

        self._study_db_id = study_db_id
