# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.breeding_methods_response_result import BreedingMethodsResponseResult  # noqa: F401,E501
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi import util


class BreedingMethodsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: BreedingMethodsResponseResult=None):  # noqa: E501
        """BreedingMethodsResponse - a model defined in Swagger

        :param metadata: The metadata of this BreedingMethodsResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this BreedingMethodsResponse.  # noqa: E501
        :type result: BreedingMethodsResponseResult
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': BreedingMethodsResponseResult
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'BreedingMethodsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The breedingMethodsResponse of this BreedingMethodsResponse.  # noqa: E501
        :rtype: BreedingMethodsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this BreedingMethodsResponse.


        :return: The metadata of this BreedingMethodsResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this BreedingMethodsResponse.


        :param metadata: The metadata of this BreedingMethodsResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> BreedingMethodsResponseResult:
        """Gets the result of this BreedingMethodsResponse.


        :return: The result of this BreedingMethodsResponse.
        :rtype: BreedingMethodsResponseResult
        """
        return self._result

    @result.setter
    def result(self, result: BreedingMethodsResponseResult):
        """Sets the result of this BreedingMethodsResponse.


        :param result: The result of this BreedingMethodsResponse.
        :type result: BreedingMethodsResponseResult
        """

        self._result = result
