# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.calls_response_result import CallsResponseResult  # noqa: F401,E501
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi import util


class CallsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: CallsResponseResult=None):  # noqa: E501
        """CallsResponse - a model defined in Swagger

        :param metadata: The metadata of this CallsResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this CallsResponse.  # noqa: E501
        :type result: CallsResponseResult
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': CallsResponseResult
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'CallsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The callsResponse of this CallsResponse.  # noqa: E501
        :rtype: CallsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this CallsResponse.


        :return: The metadata of this CallsResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this CallsResponse.


        :param metadata: The metadata of this CallsResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> CallsResponseResult:
        """Gets the result of this CallsResponse.


        :return: The result of this CallsResponse.
        :rtype: CallsResponseResult
        """
        return self._result

    @result.setter
    def result(self, result: CallsResponseResult):
        """Sets the result of this CallsResponse.


        :param result: The result of this CallsResponse.
        :type result: CallsResponseResult
        """

        self._result = result
