# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi import util


class DataLink(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data_link_name: str=None, name: str=None, type: str=None, url: str=None):  # noqa: E501
        """DataLink - a model defined in Swagger

        :param data_link_name: The data_link_name of this DataLink.  # noqa: E501
        :type data_link_name: str
        :param name: The name of this DataLink.  # noqa: E501
        :type name: str
        :param type: The type of this DataLink.  # noqa: E501
        :type type: str
        :param url: The url of this DataLink.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'data_link_name': str,
            'name': str,
            'type': str,
            'url': str
        }

        self.attribute_map = {
            'data_link_name': 'dataLinkName',
            'name': 'name',
            'type': 'type',
            'url': 'url'
        }

        self._data_link_name = data_link_name
        self._name = name
        self._type = type
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'DataLink':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dataLink of this DataLink.  # noqa: E501
        :rtype: DataLink
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_link_name(self) -> str:
        """Gets the data_link_name of this DataLink.

        The name of the external data link  # noqa: E501

        :return: The data_link_name of this DataLink.
        :rtype: str
        """
        return self._data_link_name

    @data_link_name.setter
    def data_link_name(self, data_link_name: str):
        """Sets the data_link_name of this DataLink.

        The name of the external data link  # noqa: E501

        :param data_link_name: The data_link_name of this DataLink.
        :type data_link_name: str
        """

        self._data_link_name = data_link_name

    @property
    def name(self) -> str:
        """Gets the name of this DataLink.

        DEPRECATED in v1.3 - Use \"dataLinkName\"  # noqa: E501

        :return: The name of this DataLink.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DataLink.

        DEPRECATED in v1.3 - Use \"dataLinkName\"  # noqa: E501

        :param name: The name of this DataLink.
        :type name: str
        """

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this DataLink.

        The type of external data link  # noqa: E501

        :return: The type of this DataLink.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this DataLink.

        The type of external data link  # noqa: E501

        :param type: The type of this DataLink.
        :type type: str
        """

        self._type = type

    @property
    def url(self) -> str:
        """Gets the url of this DataLink.

        The URL which links to external data  # noqa: E501

        :return: The url of this DataLink.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this DataLink.

        The URL which links to external data  # noqa: E501

        :param url: The url of this DataLink.
        :type url: str
        """

        self._url = url
