# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.germplasm_markerprofiles_list import GermplasmMarkerprofilesList  # noqa: F401,E501
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi import util


class GermplasmMarkerprofilesListResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: GermplasmMarkerprofilesList=None):  # noqa: E501
        """GermplasmMarkerprofilesListResponse - a model defined in Swagger

        :param metadata: The metadata of this GermplasmMarkerprofilesListResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this GermplasmMarkerprofilesListResponse.  # noqa: E501
        :type result: GermplasmMarkerprofilesList
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': GermplasmMarkerprofilesList
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'GermplasmMarkerprofilesListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The germplasmMarkerprofilesListResponse of this GermplasmMarkerprofilesListResponse.  # noqa: E501
        :rtype: GermplasmMarkerprofilesListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this GermplasmMarkerprofilesListResponse.


        :return: The metadata of this GermplasmMarkerprofilesListResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this GermplasmMarkerprofilesListResponse.


        :param metadata: The metadata of this GermplasmMarkerprofilesListResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> GermplasmMarkerprofilesList:
        """Gets the result of this GermplasmMarkerprofilesListResponse.


        :return: The result of this GermplasmMarkerprofilesListResponse.
        :rtype: GermplasmMarkerprofilesList
        """
        return self._result

    @result.setter
    def result(self, result: GermplasmMarkerprofilesList):
        """Sets the result of this GermplasmMarkerprofilesListResponse.


        :param result: The result of this GermplasmMarkerprofilesListResponse.
        :type result: GermplasmMarkerprofilesList
        """

        self._result = result
