# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.locations_response_result import LocationsResponseResult  # noqa: F401,E501
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi import util


class LocationsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: LocationsResponseResult=None):  # noqa: E501
        """LocationsResponse - a model defined in Swagger

        :param metadata: The metadata of this LocationsResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this LocationsResponse.  # noqa: E501
        :type result: LocationsResponseResult
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': LocationsResponseResult
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'LocationsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The locationsResponse of this LocationsResponse.  # noqa: E501
        :rtype: LocationsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this LocationsResponse.


        :return: The metadata of this LocationsResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this LocationsResponse.


        :param metadata: The metadata of this LocationsResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> LocationsResponseResult:
        """Gets the result of this LocationsResponse.


        :return: The result of this LocationsResponse.
        :rtype: LocationsResponseResult
        """
        return self._result

    @result.setter
    def result(self, result: LocationsResponseResult):
        """Sets the result of this LocationsResponse.


        :param result: The result of this LocationsResponse.
        :type result: LocationsResponseResult
        """

        self._result = result
