# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.marker_profile_descriptions_response_result import MarkerProfileDescriptionsResponseResult  # noqa: F401,E501
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi import util


class MarkerProfileDescriptionsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: MarkerProfileDescriptionsResponseResult=None):  # noqa: E501
        """MarkerProfileDescriptionsResponse - a model defined in Swagger

        :param metadata: The metadata of this MarkerProfileDescriptionsResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this MarkerProfileDescriptionsResponse.  # noqa: E501
        :type result: MarkerProfileDescriptionsResponseResult
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': MarkerProfileDescriptionsResponseResult
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'MarkerProfileDescriptionsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The markerProfileDescriptionsResponse of this MarkerProfileDescriptionsResponse.  # noqa: E501
        :rtype: MarkerProfileDescriptionsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this MarkerProfileDescriptionsResponse.


        :return: The metadata of this MarkerProfileDescriptionsResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this MarkerProfileDescriptionsResponse.


        :param metadata: The metadata of this MarkerProfileDescriptionsResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> MarkerProfileDescriptionsResponseResult:
        """Gets the result of this MarkerProfileDescriptionsResponse.


        :return: The result of this MarkerProfileDescriptionsResponse.
        :rtype: MarkerProfileDescriptionsResponseResult
        """
        return self._result

    @result.setter
    def result(self, result: MarkerProfileDescriptionsResponseResult):
        """Sets the result of this MarkerProfileDescriptionsResponse.


        :param result: The result of this MarkerProfileDescriptionsResponse.
        :type result: MarkerProfileDescriptionsResponseResult
        """

        self._result = result
