# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi import util


class MetadataPagination(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, current_page: int=None, page_size: int=None, total_count: int=None, total_pages: int=None):  # noqa: E501
        """MetadataPagination - a model defined in Swagger

        :param current_page: The current_page of this MetadataPagination.  # noqa: E501
        :type current_page: int
        :param page_size: The page_size of this MetadataPagination.  # noqa: E501
        :type page_size: int
        :param total_count: The total_count of this MetadataPagination.  # noqa: E501
        :type total_count: int
        :param total_pages: The total_pages of this MetadataPagination.  # noqa: E501
        :type total_pages: int
        """
        self.swagger_types = {
            'current_page': int,
            'page_size': int,
            'total_count': int,
            'total_pages': int
        }

        self.attribute_map = {
            'current_page': 'currentPage',
            'page_size': 'pageSize',
            'total_count': 'totalCount',
            'total_pages': 'totalPages'
        }

        self._current_page = current_page
        self._page_size = page_size
        self._total_count = total_count
        self._total_pages = total_pages

    @classmethod
    def from_dict(cls, dikt) -> 'MetadataPagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The metadata_pagination of this MetadataPagination.  # noqa: E501
        :rtype: MetadataPagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_page(self) -> int:
        """Gets the current_page of this MetadataPagination.


        :return: The current_page of this MetadataPagination.
        :rtype: int
        """
        return self._current_page

    @current_page.setter
    def current_page(self, current_page: int):
        """Sets the current_page of this MetadataPagination.


        :param current_page: The current_page of this MetadataPagination.
        :type current_page: int
        """

        self._current_page = current_page

    @property
    def page_size(self) -> int:
        """Gets the page_size of this MetadataPagination.


        :return: The page_size of this MetadataPagination.
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size: int):
        """Sets the page_size of this MetadataPagination.


        :param page_size: The page_size of this MetadataPagination.
        :type page_size: int
        """

        self._page_size = page_size

    @property
    def total_count(self) -> int:
        """Gets the total_count of this MetadataPagination.


        :return: The total_count of this MetadataPagination.
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count: int):
        """Sets the total_count of this MetadataPagination.


        :param total_count: The total_count of this MetadataPagination.
        :type total_count: int
        """

        self._total_count = total_count

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this MetadataPagination.


        :return: The total_pages of this MetadataPagination.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this MetadataPagination.


        :param total_pages: The total_pages of this MetadataPagination.
        :type total_pages: int
        """

        self._total_pages = total_pages
