# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.new_observations_request_observations import NewObservationsRequestObservations  # noqa: F401,E501
from bety_brapi import util


class NewObservationsRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, observations: List[NewObservationsRequestObservations]=None):  # noqa: E501
        """NewObservationsRequest - a model defined in Swagger

        :param observations: The observations of this NewObservationsRequest.  # noqa: E501
        :type observations: List[NewObservationsRequestObservations]
        """
        self.swagger_types = {
            'observations': List[NewObservationsRequestObservations]
        }

        self.attribute_map = {
            'observations': 'observations'
        }

        self._observations = observations

    @classmethod
    def from_dict(cls, dikt) -> 'NewObservationsRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The newObservationsRequest of this NewObservationsRequest.  # noqa: E501
        :rtype: NewObservationsRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def observations(self) -> List[NewObservationsRequestObservations]:
        """Gets the observations of this NewObservationsRequest.

        List of observation references to be created or updated  # noqa: E501

        :return: The observations of this NewObservationsRequest.
        :rtype: List[NewObservationsRequestObservations]
        """
        return self._observations

    @observations.setter
    def observations(self, observations: List[NewObservationsRequestObservations]):
        """Sets the observations of this NewObservationsRequest.

        List of observation references to be created or updated  # noqa: E501

        :param observations: The observations of this NewObservationsRequest.
        :type observations: List[NewObservationsRequestObservations]
        """

        self._observations = observations
