# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi import util


class NewObservationsRequestObservations(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, collector: str=None, observation_db_id: str=None, observation_time_stamp: datetime=None, observation_unit_db_id: str=None, observation_variable_db_id: str=None, value: str=None):  # noqa: E501
        """NewObservationsRequestObservations - a model defined in Swagger

        :param collector: The collector of this NewObservationsRequestObservations.  # noqa: E501
        :type collector: str
        :param observation_db_id: The observation_db_id of this NewObservationsRequestObservations.  # noqa: E501
        :type observation_db_id: str
        :param observation_time_stamp: The observation_time_stamp of this NewObservationsRequestObservations.  # noqa: E501
        :type observation_time_stamp: datetime
        :param observation_unit_db_id: The observation_unit_db_id of this NewObservationsRequestObservations.  # noqa: E501
        :type observation_unit_db_id: str
        :param observation_variable_db_id: The observation_variable_db_id of this NewObservationsRequestObservations.  # noqa: E501
        :type observation_variable_db_id: str
        :param value: The value of this NewObservationsRequestObservations.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'collector': str,
            'observation_db_id': str,
            'observation_time_stamp': datetime,
            'observation_unit_db_id': str,
            'observation_variable_db_id': str,
            'value': str
        }

        self.attribute_map = {
            'collector': 'collector',
            'observation_db_id': 'observationDbId',
            'observation_time_stamp': 'observationTimeStamp',
            'observation_unit_db_id': 'observationUnitDbId',
            'observation_variable_db_id': 'observationVariableDbId',
            'value': 'value'
        }

        self._collector = collector
        self._observation_db_id = observation_db_id
        self._observation_time_stamp = observation_time_stamp
        self._observation_unit_db_id = observation_unit_db_id
        self._observation_variable_db_id = observation_variable_db_id
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'NewObservationsRequestObservations':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The newObservationsRequest_observations of this NewObservationsRequestObservations.  # noqa: E501
        :rtype: NewObservationsRequestObservations
        """
        return util.deserialize_model(dikt, cls)

    @property
    def collector(self) -> str:
        """Gets the collector of this NewObservationsRequestObservations.


        :return: The collector of this NewObservationsRequestObservations.
        :rtype: str
        """
        return self._collector

    @collector.setter
    def collector(self, collector: str):
        """Sets the collector of this NewObservationsRequestObservations.


        :param collector: The collector of this NewObservationsRequestObservations.
        :type collector: str
        """

        self._collector = collector

    @property
    def observation_db_id(self) -> str:
        """Gets the observation_db_id of this NewObservationsRequestObservations.


        :return: The observation_db_id of this NewObservationsRequestObservations.
        :rtype: str
        """
        return self._observation_db_id

    @observation_db_id.setter
    def observation_db_id(self, observation_db_id: str):
        """Sets the observation_db_id of this NewObservationsRequestObservations.


        :param observation_db_id: The observation_db_id of this NewObservationsRequestObservations.
        :type observation_db_id: str
        """

        self._observation_db_id = observation_db_id

    @property
    def observation_time_stamp(self) -> datetime:
        """Gets the observation_time_stamp of this NewObservationsRequestObservations.


        :return: The observation_time_stamp of this NewObservationsRequestObservations.
        :rtype: datetime
        """
        return self._observation_time_stamp

    @observation_time_stamp.setter
    def observation_time_stamp(self, observation_time_stamp: datetime):
        """Sets the observation_time_stamp of this NewObservationsRequestObservations.


        :param observation_time_stamp: The observation_time_stamp of this NewObservationsRequestObservations.
        :type observation_time_stamp: datetime
        """

        self._observation_time_stamp = observation_time_stamp

    @property
    def observation_unit_db_id(self) -> str:
        """Gets the observation_unit_db_id of this NewObservationsRequestObservations.


        :return: The observation_unit_db_id of this NewObservationsRequestObservations.
        :rtype: str
        """
        return self._observation_unit_db_id

    @observation_unit_db_id.setter
    def observation_unit_db_id(self, observation_unit_db_id: str):
        """Sets the observation_unit_db_id of this NewObservationsRequestObservations.


        :param observation_unit_db_id: The observation_unit_db_id of this NewObservationsRequestObservations.
        :type observation_unit_db_id: str
        """

        self._observation_unit_db_id = observation_unit_db_id

    @property
    def observation_variable_db_id(self) -> str:
        """Gets the observation_variable_db_id of this NewObservationsRequestObservations.


        :return: The observation_variable_db_id of this NewObservationsRequestObservations.
        :rtype: str
        """
        return self._observation_variable_db_id

    @observation_variable_db_id.setter
    def observation_variable_db_id(self, observation_variable_db_id: str):
        """Sets the observation_variable_db_id of this NewObservationsRequestObservations.


        :param observation_variable_db_id: The observation_variable_db_id of this NewObservationsRequestObservations.
        :type observation_variable_db_id: str
        """

        self._observation_variable_db_id = observation_variable_db_id

    @property
    def value(self) -> str:
        """Gets the value of this NewObservationsRequestObservations.


        :return: The value of this NewObservationsRequestObservations.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this NewObservationsRequestObservations.


        :param value: The value of this NewObservationsRequestObservations.
        :type value: str
        """

        self._value = value
