# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi import util


class NewObservationUnitDbIds(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, observation_unit_db_ids: List[str]=None):  # noqa: E501
        """NewObservationUnitDbIds - a model defined in Swagger

        :param observation_unit_db_ids: The observation_unit_db_ids of this NewObservationUnitDbIds.  # noqa: E501
        :type observation_unit_db_ids: List[str]
        """
        self.swagger_types = {
            'observation_unit_db_ids': List[str]
        }

        self.attribute_map = {
            'observation_unit_db_ids': 'observationUnitDbIds'
        }

        self._observation_unit_db_ids = observation_unit_db_ids

    @classmethod
    def from_dict(cls, dikt) -> 'NewObservationUnitDbIds':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The newObservationUnitDbIds of this NewObservationUnitDbIds.  # noqa: E501
        :rtype: NewObservationUnitDbIds
        """
        return util.deserialize_model(dikt, cls)

    @property
    def observation_unit_db_ids(self) -> List[str]:
        """Gets the observation_unit_db_ids of this NewObservationUnitDbIds.

        List of observation unit references which have been created or updated  # noqa: E501

        :return: The observation_unit_db_ids of this NewObservationUnitDbIds.
        :rtype: List[str]
        """
        return self._observation_unit_db_ids

    @observation_unit_db_ids.setter
    def observation_unit_db_ids(self, observation_unit_db_ids: List[str]):
        """Sets the observation_unit_db_ids of this NewObservationUnitDbIds.

        List of observation unit references which have been created or updated  # noqa: E501

        :param observation_unit_db_ids: The observation_unit_db_ids of this NewObservationUnitDbIds.
        :type observation_unit_db_ids: List[str]
        """

        self._observation_unit_db_ids = observation_unit_db_ids
