# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.new_observations_request_observations import NewObservationsRequestObservations  # noqa: F401,E501
from bety_brapi import util


class NewObservationsRequestDeprecatedData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, observatio_unit_db_id: str=None, observations: List[NewObservationsRequestObservations]=None, study_db_id: float=None):  # noqa: E501
        """NewObservationsRequestDeprecatedData - a model defined in Swagger

        :param observatio_unit_db_id: The observatio_unit_db_id of this NewObservationsRequestDeprecatedData.  # noqa: E501
        :type observatio_unit_db_id: str
        :param observations: The observations of this NewObservationsRequestDeprecatedData.  # noqa: E501
        :type observations: List[NewObservationsRequestObservations]
        :param study_db_id: The study_db_id of this NewObservationsRequestDeprecatedData.  # noqa: E501
        :type study_db_id: float
        """
        self.swagger_types = {
            'observatio_unit_db_id': str,
            'observations': List[NewObservationsRequestObservations],
            'study_db_id': float
        }

        self.attribute_map = {
            'observatio_unit_db_id': 'observatioUnitDbId',
            'observations': 'observations',
            'study_db_id': 'studyDbId'
        }

        self._observatio_unit_db_id = observatio_unit_db_id
        self._observations = observations
        self._study_db_id = study_db_id

    @classmethod
    def from_dict(cls, dikt) -> 'NewObservationsRequestDeprecatedData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The newObservationsRequestDeprecated_data of this NewObservationsRequestDeprecatedData.  # noqa: E501
        :rtype: NewObservationsRequestDeprecatedData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def observatio_unit_db_id(self) -> str:
        """Gets the observatio_unit_db_id of this NewObservationsRequestDeprecatedData.


        :return: The observatio_unit_db_id of this NewObservationsRequestDeprecatedData.
        :rtype: str
        """
        return self._observatio_unit_db_id

    @observatio_unit_db_id.setter
    def observatio_unit_db_id(self, observatio_unit_db_id: str):
        """Sets the observatio_unit_db_id of this NewObservationsRequestDeprecatedData.


        :param observatio_unit_db_id: The observatio_unit_db_id of this NewObservationsRequestDeprecatedData.
        :type observatio_unit_db_id: str
        """

        self._observatio_unit_db_id = observatio_unit_db_id

    @property
    def observations(self) -> List[NewObservationsRequestObservations]:
        """Gets the observations of this NewObservationsRequestDeprecatedData.


        :return: The observations of this NewObservationsRequestDeprecatedData.
        :rtype: List[NewObservationsRequestObservations]
        """
        return self._observations

    @observations.setter
    def observations(self, observations: List[NewObservationsRequestObservations]):
        """Sets the observations of this NewObservationsRequestDeprecatedData.


        :param observations: The observations of this NewObservationsRequestDeprecatedData.
        :type observations: List[NewObservationsRequestObservations]
        """

        self._observations = observations

    @property
    def study_db_id(self) -> float:
        """Gets the study_db_id of this NewObservationsRequestDeprecatedData.


        :return: The study_db_id of this NewObservationsRequestDeprecatedData.
        :rtype: float
        """
        return self._study_db_id

    @study_db_id.setter
    def study_db_id(self, study_db_id: float):
        """Sets the study_db_id of this NewObservationsRequestDeprecatedData.


        :param study_db_id: The study_db_id of this NewObservationsRequestDeprecatedData.
        :type study_db_id: float
        """

        self._study_db_id = study_db_id
