# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi import util


class NewObservationDbIdsObservations(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, observation_db_id: str=None, observation_unit_db_id: str=None, observation_variable_db_id: str=None):  # noqa: E501
        """NewObservationDbIdsObservations - a model defined in Swagger

        :param observation_db_id: The observation_db_id of this NewObservationDbIdsObservations.  # noqa: E501
        :type observation_db_id: str
        :param observation_unit_db_id: The observation_unit_db_id of this NewObservationDbIdsObservations.  # noqa: E501
        :type observation_unit_db_id: str
        :param observation_variable_db_id: The observation_variable_db_id of this NewObservationDbIdsObservations.  # noqa: E501
        :type observation_variable_db_id: str
        """
        self.swagger_types = {
            'observation_db_id': str,
            'observation_unit_db_id': str,
            'observation_variable_db_id': str
        }

        self.attribute_map = {
            'observation_db_id': 'observationDbId',
            'observation_unit_db_id': 'observationUnitDbId',
            'observation_variable_db_id': 'observationVariableDbId'
        }

        self._observation_db_id = observation_db_id
        self._observation_unit_db_id = observation_unit_db_id
        self._observation_variable_db_id = observation_variable_db_id

    @classmethod
    def from_dict(cls, dikt) -> 'NewObservationDbIdsObservations':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The newObservationDbIds_observations of this NewObservationDbIdsObservations.  # noqa: E501
        :rtype: NewObservationDbIdsObservations
        """
        return util.deserialize_model(dikt, cls)

    @property
    def observation_db_id(self) -> str:
        """Gets the observation_db_id of this NewObservationDbIdsObservations.


        :return: The observation_db_id of this NewObservationDbIdsObservations.
        :rtype: str
        """
        return self._observation_db_id

    @observation_db_id.setter
    def observation_db_id(self, observation_db_id: str):
        """Sets the observation_db_id of this NewObservationDbIdsObservations.


        :param observation_db_id: The observation_db_id of this NewObservationDbIdsObservations.
        :type observation_db_id: str
        """

        self._observation_db_id = observation_db_id

    @property
    def observation_unit_db_id(self) -> str:
        """Gets the observation_unit_db_id of this NewObservationDbIdsObservations.


        :return: The observation_unit_db_id of this NewObservationDbIdsObservations.
        :rtype: str
        """
        return self._observation_unit_db_id

    @observation_unit_db_id.setter
    def observation_unit_db_id(self, observation_unit_db_id: str):
        """Sets the observation_unit_db_id of this NewObservationDbIdsObservations.


        :param observation_unit_db_id: The observation_unit_db_id of this NewObservationDbIdsObservations.
        :type observation_unit_db_id: str
        """

        self._observation_unit_db_id = observation_unit_db_id

    @property
    def observation_variable_db_id(self) -> str:
        """Gets the observation_variable_db_id of this NewObservationDbIdsObservations.


        :return: The observation_variable_db_id of this NewObservationDbIdsObservations.
        :rtype: str
        """
        return self._observation_variable_db_id

    @observation_variable_db_id.setter
    def observation_variable_db_id(self, observation_variable_db_id: str):
        """Sets the observation_variable_db_id of this NewObservationDbIdsObservations.


        :param observation_variable_db_id: The observation_variable_db_id of this NewObservationDbIdsObservations.
        :type observation_variable_db_id: str
        """

        self._observation_variable_db_id = observation_variable_db_id
