# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi.models.new_observations_request_deprecated import NewObservationsRequestDeprecated  # noqa: F401,E501
from bety_brapi import util


class NewObservationsRequestWrapperDeprecated(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: NewObservationsRequestDeprecated=None):  # noqa: E501
        """NewObservationsRequestWrapperDeprecated - a model defined in Swagger

        :param metadata: The metadata of this NewObservationsRequestWrapperDeprecated.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this NewObservationsRequestWrapperDeprecated.  # noqa: E501
        :type result: NewObservationsRequestDeprecated
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': NewObservationsRequestDeprecated
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'NewObservationsRequestWrapperDeprecated':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The newObservationsRequestWrapperDeprecated of this NewObservationsRequestWrapperDeprecated.  # noqa: E501
        :rtype: NewObservationsRequestWrapperDeprecated
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this NewObservationsRequestWrapperDeprecated.


        :return: The metadata of this NewObservationsRequestWrapperDeprecated.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this NewObservationsRequestWrapperDeprecated.


        :param metadata: The metadata of this NewObservationsRequestWrapperDeprecated.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> NewObservationsRequestDeprecated:
        """Gets the result of this NewObservationsRequestWrapperDeprecated.


        :return: The result of this NewObservationsRequestWrapperDeprecated.
        :rtype: NewObservationsRequestDeprecated
        """
        return self._result

    @result.setter
    def result(self, result: NewObservationsRequestDeprecated):
        """Sets the result of this NewObservationsRequestWrapperDeprecated.


        :param result: The result of this NewObservationsRequestWrapperDeprecated.
        :type result: NewObservationsRequestDeprecated
        """

        self._result = result
