# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi.models.observation_units_response1_result import ObservationUnitsResponse1Result  # noqa: F401,E501
from bety_brapi import util


class ObservationUnitsResponse1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: ObservationUnitsResponse1Result=None):  # noqa: E501
        """ObservationUnitsResponse1 - a model defined in Swagger

        :param metadata: The metadata of this ObservationUnitsResponse1.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this ObservationUnitsResponse1.  # noqa: E501
        :type result: ObservationUnitsResponse1Result
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': ObservationUnitsResponse1Result
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'ObservationUnitsResponse1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The observationUnitsResponse_1 of this ObservationUnitsResponse1.  # noqa: E501
        :rtype: ObservationUnitsResponse1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this ObservationUnitsResponse1.


        :return: The metadata of this ObservationUnitsResponse1.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this ObservationUnitsResponse1.


        :param metadata: The metadata of this ObservationUnitsResponse1.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> ObservationUnitsResponse1Result:
        """Gets the result of this ObservationUnitsResponse1.


        :return: The result of this ObservationUnitsResponse1.
        :rtype: ObservationUnitsResponse1Result
        """
        return self._result

    @result.setter
    def result(self, result: ObservationUnitsResponse1Result):
        """Sets the result of this ObservationUnitsResponse1.


        :param result: The result of this ObservationUnitsResponse1.
        :type result: ObservationUnitsResponse1Result
        """

        self._result = result
