# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi.models.observation_levels_response_result import ObservationLevelsResponseResult  # noqa: F401,E501
from bety_brapi import util


class ObservationLevelsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: ObservationLevelsResponseResult=None):  # noqa: E501
        """ObservationLevelsResponse - a model defined in Swagger

        :param metadata: The metadata of this ObservationLevelsResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this ObservationLevelsResponse.  # noqa: E501
        :type result: ObservationLevelsResponseResult
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': ObservationLevelsResponseResult
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'ObservationLevelsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The observationLevelsResponse of this ObservationLevelsResponse.  # noqa: E501
        :rtype: ObservationLevelsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this ObservationLevelsResponse.


        :return: The metadata of this ObservationLevelsResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this ObservationLevelsResponse.


        :param metadata: The metadata of this ObservationLevelsResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> ObservationLevelsResponseResult:
        """Gets the result of this ObservationLevelsResponse.


        :return: The result of this ObservationLevelsResponse.
        :rtype: ObservationLevelsResponseResult
        """
        return self._result

    @result.setter
    def result(self, result: ObservationLevelsResponseResult):
        """Sets the result of this ObservationLevelsResponse.


        :param result: The result of this ObservationLevelsResponse.
        :type result: ObservationLevelsResponseResult
        """

        self._result = result
