# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi.models.observations_response_result import ObservationsResponseResult  # noqa: F401,E501
from bety_brapi import util


class ObservationsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: ObservationsResponseResult=None):  # noqa: E501
        """ObservationsResponse - a model defined in Swagger

        :param metadata: The metadata of this ObservationsResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this ObservationsResponse.  # noqa: E501
        :type result: ObservationsResponseResult
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': ObservationsResponseResult
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'ObservationsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The observationsResponse of this ObservationsResponse.  # noqa: E501
        :rtype: ObservationsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this ObservationsResponse.


        :return: The metadata of this ObservationsResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this ObservationsResponse.


        :param metadata: The metadata of this ObservationsResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> ObservationsResponseResult:
        """Gets the result of this ObservationsResponse.


        :return: The result of this ObservationsResponse.
        :rtype: ObservationsResponseResult
        """
        return self._result

    @result.setter
    def result(self, result: ObservationsResponseResult):
        """Sets the result of this ObservationsResponse.


        :param result: The result of this ObservationsResponse.
        :type result: ObservationsResponseResult
        """

        self._result = result
