# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi.models.pedigree import Pedigree  # noqa: F401,E501
from bety_brapi import util


class PedigreeResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: Pedigree=None):  # noqa: E501
        """PedigreeResponse - a model defined in Swagger

        :param metadata: The metadata of this PedigreeResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this PedigreeResponse.  # noqa: E501
        :type result: Pedigree
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': Pedigree
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'PedigreeResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The pedigreeResponse of this PedigreeResponse.  # noqa: E501
        :rtype: PedigreeResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this PedigreeResponse.


        :return: The metadata of this PedigreeResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this PedigreeResponse.


        :param metadata: The metadata of this PedigreeResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> Pedigree:
        """Gets the result of this PedigreeResponse.


        :return: The result of this PedigreeResponse.
        :rtype: Pedigree
        """
        return self._result

    @result.setter
    def result(self, result: Pedigree):
        """Sets the result of this PedigreeResponse.


        :param result: The result of this PedigreeResponse.
        :type result: Pedigree
        """

        self._result = result
