# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.phenotypes_request_data import PhenotypesRequestData  # noqa: F401,E501
from bety_brapi import util


class PhenotypesRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data: List[PhenotypesRequestData]=None):  # noqa: E501
        """PhenotypesRequest - a model defined in Swagger

        :param data: The data of this PhenotypesRequest.  # noqa: E501
        :type data: List[PhenotypesRequestData]
        """
        self.swagger_types = {
            'data': List[PhenotypesRequestData]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'PhenotypesRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The phenotypesRequest of this PhenotypesRequest.  # noqa: E501
        :rtype: PhenotypesRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[PhenotypesRequestData]:
        """Gets the data of this PhenotypesRequest.

        Matrix of observation data recorded for different observation variables across different observation units  # noqa: E501

        :return: The data of this PhenotypesRequest.
        :rtype: List[PhenotypesRequestData]
        """
        return self._data

    @data.setter
    def data(self, data: List[PhenotypesRequestData]):
        """Sets the data of this PhenotypesRequest.

        Matrix of observation data recorded for different observation variables across different observation units  # noqa: E501

        :param data: The data of this PhenotypesRequest.
        :type data: List[PhenotypesRequestData]
        """

        self._data = data
