# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi import util


class PhenotypesRequestObservation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, collector: str=None, observation_db_id: str=None, observation_time_stamp: datetime=None, observation_variable_db_id: str=None, observation_variable_name: str=None, season: str=None, value: str=None):  # noqa: E501
        """PhenotypesRequestObservation - a model defined in Swagger

        :param collector: The collector of this PhenotypesRequestObservation.  # noqa: E501
        :type collector: str
        :param observation_db_id: The observation_db_id of this PhenotypesRequestObservation.  # noqa: E501
        :type observation_db_id: str
        :param observation_time_stamp: The observation_time_stamp of this PhenotypesRequestObservation.  # noqa: E501
        :type observation_time_stamp: datetime
        :param observation_variable_db_id: The observation_variable_db_id of this PhenotypesRequestObservation.  # noqa: E501
        :type observation_variable_db_id: str
        :param observation_variable_name: The observation_variable_name of this PhenotypesRequestObservation.  # noqa: E501
        :type observation_variable_name: str
        :param season: The season of this PhenotypesRequestObservation.  # noqa: E501
        :type season: str
        :param value: The value of this PhenotypesRequestObservation.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'collector': str,
            'observation_db_id': str,
            'observation_time_stamp': datetime,
            'observation_variable_db_id': str,
            'observation_variable_name': str,
            'season': str,
            'value': str
        }

        self.attribute_map = {
            'collector': 'collector',
            'observation_db_id': 'observationDbId',
            'observation_time_stamp': 'observationTimeStamp',
            'observation_variable_db_id': 'observationVariableDbId',
            'observation_variable_name': 'observationVariableName',
            'season': 'season',
            'value': 'value'
        }

        self._collector = collector
        self._observation_db_id = observation_db_id
        self._observation_time_stamp = observation_time_stamp
        self._observation_variable_db_id = observation_variable_db_id
        self._observation_variable_name = observation_variable_name
        self._season = season
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'PhenotypesRequestObservation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The phenotypesRequestObservation of this PhenotypesRequestObservation.  # noqa: E501
        :rtype: PhenotypesRequestObservation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def collector(self) -> str:
        """Gets the collector of this PhenotypesRequestObservation.

        The name or identifier of the entity which collected the observation  # noqa: E501

        :return: The collector of this PhenotypesRequestObservation.
        :rtype: str
        """
        return self._collector

    @collector.setter
    def collector(self, collector: str):
        """Sets the collector of this PhenotypesRequestObservation.

        The name or identifier of the entity which collected the observation  # noqa: E501

        :param collector: The collector of this PhenotypesRequestObservation.
        :type collector: str
        """
        if collector is None:
            raise ValueError("Invalid value for `collector`, must not be `None`")  # noqa: E501

        self._collector = collector

    @property
    def observation_db_id(self) -> str:
        """Gets the observation_db_id of this PhenotypesRequestObservation.

        The ID which uniquely identifies an observation  # noqa: E501

        :return: The observation_db_id of this PhenotypesRequestObservation.
        :rtype: str
        """
        return self._observation_db_id

    @observation_db_id.setter
    def observation_db_id(self, observation_db_id: str):
        """Sets the observation_db_id of this PhenotypesRequestObservation.

        The ID which uniquely identifies an observation  # noqa: E501

        :param observation_db_id: The observation_db_id of this PhenotypesRequestObservation.
        :type observation_db_id: str
        """

        self._observation_db_id = observation_db_id

    @property
    def observation_time_stamp(self) -> datetime:
        """Gets the observation_time_stamp of this PhenotypesRequestObservation.

        The date and time  when this observation was made   # noqa: E501

        :return: The observation_time_stamp of this PhenotypesRequestObservation.
        :rtype: datetime
        """
        return self._observation_time_stamp

    @observation_time_stamp.setter
    def observation_time_stamp(self, observation_time_stamp: datetime):
        """Sets the observation_time_stamp of this PhenotypesRequestObservation.

        The date and time  when this observation was made   # noqa: E501

        :param observation_time_stamp: The observation_time_stamp of this PhenotypesRequestObservation.
        :type observation_time_stamp: datetime
        """
        if observation_time_stamp is None:
            raise ValueError("Invalid value for `observation_time_stamp`, must not be `None`")  # noqa: E501

        self._observation_time_stamp = observation_time_stamp

    @property
    def observation_variable_db_id(self) -> str:
        """Gets the observation_variable_db_id of this PhenotypesRequestObservation.

        Variable unique identifier  # noqa: E501

        :return: The observation_variable_db_id of this PhenotypesRequestObservation.
        :rtype: str
        """
        return self._observation_variable_db_id

    @observation_variable_db_id.setter
    def observation_variable_db_id(self, observation_variable_db_id: str):
        """Sets the observation_variable_db_id of this PhenotypesRequestObservation.

        Variable unique identifier  # noqa: E501

        :param observation_variable_db_id: The observation_variable_db_id of this PhenotypesRequestObservation.
        :type observation_variable_db_id: str
        """
        if observation_variable_db_id is None:
            raise ValueError("Invalid value for `observation_variable_db_id`, must not be `None`")  # noqa: E501

        self._observation_variable_db_id = observation_variable_db_id

    @property
    def observation_variable_name(self) -> str:
        """Gets the observation_variable_name of this PhenotypesRequestObservation.

        A human readable name for an observation variable  # noqa: E501

        :return: The observation_variable_name of this PhenotypesRequestObservation.
        :rtype: str
        """
        return self._observation_variable_name

    @observation_variable_name.setter
    def observation_variable_name(self, observation_variable_name: str):
        """Sets the observation_variable_name of this PhenotypesRequestObservation.

        A human readable name for an observation variable  # noqa: E501

        :param observation_variable_name: The observation_variable_name of this PhenotypesRequestObservation.
        :type observation_variable_name: str
        """
        if observation_variable_name is None:
            raise ValueError("Invalid value for `observation_variable_name`, must not be `None`")  # noqa: E501

        self._observation_variable_name = observation_variable_name

    @property
    def season(self) -> str:
        """Gets the season of this PhenotypesRequestObservation.

        The season when the observation data was collected  # noqa: E501

        :return: The season of this PhenotypesRequestObservation.
        :rtype: str
        """
        return self._season

    @season.setter
    def season(self, season: str):
        """Sets the season of this PhenotypesRequestObservation.

        The season when the observation data was collected  # noqa: E501

        :param season: The season of this PhenotypesRequestObservation.
        :type season: str
        """

        self._season = season

    @property
    def value(self) -> str:
        """Gets the value of this PhenotypesRequestObservation.

        The value of the data collected as an observation  # noqa: E501

        :return: The value of this PhenotypesRequestObservation.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this PhenotypesRequestObservation.

        The value of the data collected as an observation  # noqa: E501

        :param value: The value of this PhenotypesRequestObservation.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
