# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi.models.sample import Sample  # noqa: F401,E501
from bety_brapi import util


class SampleResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: Sample=None):  # noqa: E501
        """SampleResponse - a model defined in Swagger

        :param metadata: The metadata of this SampleResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this SampleResponse.  # noqa: E501
        :type result: Sample
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': Sample
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'SampleResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The sampleResponse of this SampleResponse.  # noqa: E501
        :rtype: SampleResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this SampleResponse.


        :return: The metadata of this SampleResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this SampleResponse.


        :param metadata: The metadata of this SampleResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> Sample:
        """Gets the result of this SampleResponse.


        :return: The result of this SampleResponse.
        :rtype: Sample
        """
        return self._result

    @result.setter
    def result(self, result: Sample):
        """Sets the result of this SampleResponse.


        :param result: The result of this SampleResponse.
        :type result: Sample
        """

        self._result = result
