# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi.models.seasons_response_result import SeasonsResponseResult  # noqa: F401,E501
from bety_brapi import util


class SeasonsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: SeasonsResponseResult=None):  # noqa: E501
        """SeasonsResponse - a model defined in Swagger

        :param metadata: The metadata of this SeasonsResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this SeasonsResponse.  # noqa: E501
        :type result: SeasonsResponseResult
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': SeasonsResponseResult
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'SeasonsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The seasonsResponse of this SeasonsResponse.  # noqa: E501
        :rtype: SeasonsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this SeasonsResponse.


        :return: The metadata of this SeasonsResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this SeasonsResponse.


        :param metadata: The metadata of this SeasonsResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> SeasonsResponseResult:
        """Gets the result of this SeasonsResponse.


        :return: The result of this SeasonsResponse.
        :rtype: SeasonsResponseResult
        """
        return self._result

    @result.setter
    def result(self, result: SeasonsResponseResult):
        """Sets the result of this SeasonsResponse.


        :param result: The result of this SeasonsResponse.
        :type result: SeasonsResponseResult
        """

        self._result = result
