# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi import util


class StudyType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, description: str=None, name: str=None, study_type_name: str=None):  # noqa: E501
        """StudyType - a model defined in Swagger

        :param description: The description of this StudyType.  # noqa: E501
        :type description: str
        :param name: The name of this StudyType.  # noqa: E501
        :type name: str
        :param study_type_name: The study_type_name of this StudyType.  # noqa: E501
        :type study_type_name: str
        """
        self.swagger_types = {
            'description': str,
            'name': str,
            'study_type_name': str
        }

        self.attribute_map = {
            'description': 'description',
            'name': 'name',
            'study_type_name': 'studyTypeName'
        }

        self._description = description
        self._name = name
        self._study_type_name = study_type_name

    @classmethod
    def from_dict(cls, dikt) -> 'StudyType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The studyType of this StudyType.  # noqa: E501
        :rtype: StudyType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """Gets the description of this StudyType.

        The description of this study type  # noqa: E501

        :return: The description of this StudyType.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this StudyType.

        The description of this study type  # noqa: E501

        :param description: The description of this StudyType.
        :type description: str
        """

        self._description = description

    @property
    def name(self) -> str:
        """Gets the name of this StudyType.

        DEPRECATED in v1.3 - Use \"studyTypeName\"  # noqa: E501

        :return: The name of this StudyType.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this StudyType.

        DEPRECATED in v1.3 - Use \"studyTypeName\"  # noqa: E501

        :param name: The name of this StudyType.
        :type name: str
        """

        self._name = name

    @property
    def study_type_name(self) -> str:
        """Gets the study_type_name of this StudyType.

        The human readable name of a study type  # noqa: E501

        :return: The study_type_name of this StudyType.
        :rtype: str
        """
        return self._study_type_name

    @study_type_name.setter
    def study_type_name(self, study_type_name: str):
        """Sets the study_type_name of this StudyType.

        The human readable name of a study type  # noqa: E501

        :param study_type_name: The study_type_name of this StudyType.
        :type study_type_name: str
        """

        self._study_type_name = study_type_name
