# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi.models.observations_table import ObservationsTable  # noqa: F401,E501
from bety_brapi import util


class StudyobservationsTableResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: ObservationsTable=None):  # noqa: E501
        """StudyobservationsTableResponse - a model defined in Swagger

        :param metadata: The metadata of this StudyobservationsTableResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this StudyobservationsTableResponse.  # noqa: E501
        :type result: ObservationsTable
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': ObservationsTable
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'StudyobservationsTableResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The studyobservationsTableResponse of this StudyobservationsTableResponse.  # noqa: E501
        :rtype: StudyobservationsTableResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this StudyobservationsTableResponse.


        :return: The metadata of this StudyobservationsTableResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this StudyobservationsTableResponse.


        :param metadata: The metadata of this StudyobservationsTableResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> ObservationsTable:
        """Gets the result of this StudyobservationsTableResponse.


        :return: The result of this StudyobservationsTableResponse.
        :rtype: ObservationsTable
        """
        return self._result

    @result.setter
    def result(self, result: ObservationsTable):
        """Sets the result of this StudyobservationsTableResponse.


        :param result: The result of this StudyobservationsTableResponse.
        :type result: ObservationsTable
        """

        self._result = result
