# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.study_layout_request_layout import StudyLayoutRequestLayout  # noqa: F401,E501
from bety_brapi import util


class StudyLayoutRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, layout: List[StudyLayoutRequestLayout]=None):  # noqa: E501
        """StudyLayoutRequest - a model defined in Swagger

        :param layout: The layout of this StudyLayoutRequest.  # noqa: E501
        :type layout: List[StudyLayoutRequestLayout]
        """
        self.swagger_types = {
            'layout': List[StudyLayoutRequestLayout]
        }

        self.attribute_map = {
            'layout': 'layout'
        }

        self._layout = layout

    @classmethod
    def from_dict(cls, dikt) -> 'StudyLayoutRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The studyLayoutRequest of this StudyLayoutRequest.  # noqa: E501
        :rtype: StudyLayoutRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def layout(self) -> List[StudyLayoutRequestLayout]:
        """Gets the layout of this StudyLayoutRequest.

        List of observation unit position data entities which need to be updated  # noqa: E501

        :return: The layout of this StudyLayoutRequest.
        :rtype: List[StudyLayoutRequestLayout]
        """
        return self._layout

    @layout.setter
    def layout(self, layout: List[StudyLayoutRequestLayout]):
        """Sets the layout of this StudyLayoutRequest.

        List of observation unit position data entities which need to be updated  # noqa: E501

        :param layout: The layout of this StudyLayoutRequest.
        :type layout: List[StudyLayoutRequestLayout]
        """

        self._layout = layout
