# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi import util


class StudySummary(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, active: str=None, additional_info: Dict[str, str]=None, end_date: date=None, location_db_id: str=None, location_name: str=None, name: str=None, program_db_id: str=None, program_name: str=None, seasons: List[str]=None, start_date: date=None, study_db_id: str=None, study_name: str=None, study_type: str=None, trial_db_id: str=None, trial_name: str=None):  # noqa: E501
        """StudySummary - a model defined in Swagger

        :param active: The active of this StudySummary.  # noqa: E501
        :type active: str
        :param additional_info: The additional_info of this StudySummary.  # noqa: E501
        :type additional_info: Dict[str, str]
        :param end_date: The end_date of this StudySummary.  # noqa: E501
        :type end_date: date
        :param location_db_id: The location_db_id of this StudySummary.  # noqa: E501
        :type location_db_id: str
        :param location_name: The location_name of this StudySummary.  # noqa: E501
        :type location_name: str
        :param name: The name of this StudySummary.  # noqa: E501
        :type name: str
        :param program_db_id: The program_db_id of this StudySummary.  # noqa: E501
        :type program_db_id: str
        :param program_name: The program_name of this StudySummary.  # noqa: E501
        :type program_name: str
        :param seasons: The seasons of this StudySummary.  # noqa: E501
        :type seasons: List[str]
        :param start_date: The start_date of this StudySummary.  # noqa: E501
        :type start_date: date
        :param study_db_id: The study_db_id of this StudySummary.  # noqa: E501
        :type study_db_id: str
        :param study_name: The study_name of this StudySummary.  # noqa: E501
        :type study_name: str
        :param study_type: The study_type of this StudySummary.  # noqa: E501
        :type study_type: str
        :param trial_db_id: The trial_db_id of this StudySummary.  # noqa: E501
        :type trial_db_id: str
        :param trial_name: The trial_name of this StudySummary.  # noqa: E501
        :type trial_name: str
        """
        self.swagger_types = {
            'active': str,
            'additional_info': Dict[str, str],
            'end_date': date,
            'location_db_id': str,
            'location_name': str,
            'name': str,
            'program_db_id': str,
            'program_name': str,
            'seasons': List[str],
            'start_date': date,
            'study_db_id': str,
            'study_name': str,
            'study_type': str,
            'trial_db_id': str,
            'trial_name': str
        }

        self.attribute_map = {
            'active': 'active',
            'additional_info': 'additionalInfo',
            'end_date': 'endDate',
            'location_db_id': 'locationDbId',
            'location_name': 'locationName',
            'name': 'name',
            'program_db_id': 'programDbId',
            'program_name': 'programName',
            'seasons': 'seasons',
            'start_date': 'startDate',
            'study_db_id': 'studyDbId',
            'study_name': 'studyName',
            'study_type': 'studyType',
            'trial_db_id': 'trialDbId',
            'trial_name': 'trialName'
        }

        self._active = active
        self._additional_info = additional_info
        self._end_date = end_date
        self._location_db_id = location_db_id
        self._location_name = location_name
        self._name = name
        self._program_db_id = program_db_id
        self._program_name = program_name
        self._seasons = seasons
        self._start_date = start_date
        self._study_db_id = study_db_id
        self._study_name = study_name
        self._study_type = study_type
        self._trial_db_id = trial_db_id
        self._trial_name = trial_name

    @classmethod
    def from_dict(cls, dikt) -> 'StudySummary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The studySummary of this StudySummary.  # noqa: E501
        :rtype: StudySummary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def active(self) -> str:
        """Gets the active of this StudySummary.

        Is this study currently active  # noqa: E501

        :return: The active of this StudySummary.
        :rtype: str
        """
        return self._active

    @active.setter
    def active(self, active: str):
        """Sets the active of this StudySummary.

        Is this study currently active  # noqa: E501

        :param active: The active of this StudySummary.
        :type active: str
        """

        self._active = active

    @property
    def additional_info(self) -> Dict[str, str]:
        """Gets the additional_info of this StudySummary.

        Additional arbitrary info  # noqa: E501

        :return: The additional_info of this StudySummary.
        :rtype: Dict[str, str]
        """
        return self._additional_info

    @additional_info.setter
    def additional_info(self, additional_info: Dict[str, str]):
        """Sets the additional_info of this StudySummary.

        Additional arbitrary info  # noqa: E501

        :param additional_info: The additional_info of this StudySummary.
        :type additional_info: Dict[str, str]
        """

        self._additional_info = additional_info

    @property
    def end_date(self) -> date:
        """Gets the end_date of this StudySummary.

        The date the study ends  # noqa: E501

        :return: The end_date of this StudySummary.
        :rtype: date
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: date):
        """Sets the end_date of this StudySummary.

        The date the study ends  # noqa: E501

        :param end_date: The end_date of this StudySummary.
        :type end_date: date
        """

        self._end_date = end_date

    @property
    def location_db_id(self) -> str:
        """Gets the location_db_id of this StudySummary.

        The ID which uniquely identifies a location  # noqa: E501

        :return: The location_db_id of this StudySummary.
        :rtype: str
        """
        return self._location_db_id

    @location_db_id.setter
    def location_db_id(self, location_db_id: str):
        """Sets the location_db_id of this StudySummary.

        The ID which uniquely identifies a location  # noqa: E501

        :param location_db_id: The location_db_id of this StudySummary.
        :type location_db_id: str
        """

        self._location_db_id = location_db_id

    @property
    def location_name(self) -> str:
        """Gets the location_name of this StudySummary.

        The human readable name for a location  # noqa: E501

        :return: The location_name of this StudySummary.
        :rtype: str
        """
        return self._location_name

    @location_name.setter
    def location_name(self, location_name: str):
        """Sets the location_name of this StudySummary.

        The human readable name for a location  # noqa: E501

        :param location_name: The location_name of this StudySummary.
        :type location_name: str
        """

        self._location_name = location_name

    @property
    def name(self) -> str:
        """Gets the name of this StudySummary.

        DEPRECATED in v1.3 - Use \"studyName\"  # noqa: E501

        :return: The name of this StudySummary.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this StudySummary.

        DEPRECATED in v1.3 - Use \"studyName\"  # noqa: E501

        :param name: The name of this StudySummary.
        :type name: str
        """

        self._name = name

    @property
    def program_db_id(self) -> str:
        """Gets the program_db_id of this StudySummary.

        The ID which uniquely identifies a program within the given database server  # noqa: E501

        :return: The program_db_id of this StudySummary.
        :rtype: str
        """
        return self._program_db_id

    @program_db_id.setter
    def program_db_id(self, program_db_id: str):
        """Sets the program_db_id of this StudySummary.

        The ID which uniquely identifies a program within the given database server  # noqa: E501

        :param program_db_id: The program_db_id of this StudySummary.
        :type program_db_id: str
        """

        self._program_db_id = program_db_id

    @property
    def program_name(self) -> str:
        """Gets the program_name of this StudySummary.

        The humane readable name of a program  # noqa: E501

        :return: The program_name of this StudySummary.
        :rtype: str
        """
        return self._program_name

    @program_name.setter
    def program_name(self, program_name: str):
        """Sets the program_name of this StudySummary.

        The humane readable name of a program  # noqa: E501

        :param program_name: The program_name of this StudySummary.
        :type program_name: str
        """

        self._program_name = program_name

    @property
    def seasons(self) -> List[str]:
        """Gets the seasons of this StudySummary.

        List of seasons over which this study was performed.  # noqa: E501

        :return: The seasons of this StudySummary.
        :rtype: List[str]
        """
        return self._seasons

    @seasons.setter
    def seasons(self, seasons: List[str]):
        """Sets the seasons of this StudySummary.

        List of seasons over which this study was performed.  # noqa: E501

        :param seasons: The seasons of this StudySummary.
        :type seasons: List[str]
        """

        self._seasons = seasons

    @property
    def start_date(self) -> date:
        """Gets the start_date of this StudySummary.

        The date this study started  # noqa: E501

        :return: The start_date of this StudySummary.
        :rtype: date
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: date):
        """Sets the start_date of this StudySummary.

        The date this study started  # noqa: E501

        :param start_date: The start_date of this StudySummary.
        :type start_date: date
        """

        self._start_date = start_date

    @property
    def study_db_id(self) -> str:
        """Gets the study_db_id of this StudySummary.

        The ID which uniquely identifies a study within the given database server  # noqa: E501

        :return: The study_db_id of this StudySummary.
        :rtype: str
        """
        return self._study_db_id

    @study_db_id.setter
    def study_db_id(self, study_db_id: str):
        """Sets the study_db_id of this StudySummary.

        The ID which uniquely identifies a study within the given database server  # noqa: E501

        :param study_db_id: The study_db_id of this StudySummary.
        :type study_db_id: str
        """

        self._study_db_id = study_db_id

    @property
    def study_name(self) -> str:
        """Gets the study_name of this StudySummary.

        The humane readable name of a study  # noqa: E501

        :return: The study_name of this StudySummary.
        :rtype: str
        """
        return self._study_name

    @study_name.setter
    def study_name(self, study_name: str):
        """Sets the study_name of this StudySummary.

        The humane readable name of a study  # noqa: E501

        :param study_name: The study_name of this StudySummary.
        :type study_name: str
        """

        self._study_name = study_name

    @property
    def study_type(self) -> str:
        """Gets the study_type of this StudySummary.

        The type of study being performed. ex. \"Yeald Trial\", etc  # noqa: E501

        :return: The study_type of this StudySummary.
        :rtype: str
        """
        return self._study_type

    @study_type.setter
    def study_type(self, study_type: str):
        """Sets the study_type of this StudySummary.

        The type of study being performed. ex. \"Yeald Trial\", etc  # noqa: E501

        :param study_type: The study_type of this StudySummary.
        :type study_type: str
        """

        self._study_type = study_type

    @property
    def trial_db_id(self) -> str:
        """Gets the trial_db_id of this StudySummary.

        The ID which uniquely identifies a trial  # noqa: E501

        :return: The trial_db_id of this StudySummary.
        :rtype: str
        """
        return self._trial_db_id

    @trial_db_id.setter
    def trial_db_id(self, trial_db_id: str):
        """Sets the trial_db_id of this StudySummary.

        The ID which uniquely identifies a trial  # noqa: E501

        :param trial_db_id: The trial_db_id of this StudySummary.
        :type trial_db_id: str
        """

        self._trial_db_id = trial_db_id

    @property
    def trial_name(self) -> str:
        """Gets the trial_name of this StudySummary.

        The human readable name of a trial  # noqa: E501

        :return: The trial_name of this StudySummary.
        :rtype: str
        """
        return self._trial_name

    @trial_name.setter
    def trial_name(self, trial_name: str):
        """Sets the trial_name of this StudySummary.

        The human readable name of a trial  # noqa: E501

        :param trial_name: The trial_name of this StudySummary.
        :type trial_name: str
        """

        self._trial_name = trial_name
