# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.metadata import Metadata  # noqa: F401,E501
from bety_brapi.models.trials_response_result import TrialsResponseResult  # noqa: F401,E501
from bety_brapi import util


class TrialsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: Metadata=None, result: TrialsResponseResult=None):  # noqa: E501
        """TrialsResponse - a model defined in Swagger

        :param metadata: The metadata of this TrialsResponse.  # noqa: E501
        :type metadata: Metadata
        :param result: The result of this TrialsResponse.  # noqa: E501
        :type result: TrialsResponseResult
        """
        self.swagger_types = {
            'metadata': Metadata,
            'result': TrialsResponseResult
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'result': 'result'
        }

        self._metadata = metadata
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TrialsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The trialsResponse of this TrialsResponse.  # noqa: E501
        :rtype: TrialsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this TrialsResponse.


        :return: The metadata of this TrialsResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this TrialsResponse.


        :param metadata: The metadata of this TrialsResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def result(self) -> TrialsResponseResult:
        """Gets the result of this TrialsResponse.


        :return: The result of this TrialsResponse.
        :rtype: TrialsResponseResult
        """
        return self._result

    @result.setter
    def result(self, result: TrialsResponseResult):
        """Sets the result of this TrialsResponse.


        :param result: The result of this TrialsResponse.
        :type result: TrialsResponseResult
        """

        self._result = result
