# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi.models.contact import Contact  # noqa: F401,E501
from bety_brapi.models.trial_dataset_authorship import TrialDatasetAuthorship  # noqa: F401,E501
from bety_brapi.models.trial_studies import TrialStudies  # noqa: F401,E501
from bety_brapi import util


class Trial(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, active: bool=None, additional_info: Dict[str, str]=None, contacts: List[Contact]=None, dataset_authorship: TrialDatasetAuthorship=None, end_date: date=None, program_db_id: str=None, program_name: str=None, start_date: date=None, studies: List[TrialStudies]=None, trial_db_id: str=None, trial_name: str=None):  # noqa: E501
        """Trial - a model defined in Swagger

        :param active: The active of this Trial.  # noqa: E501
        :type active: bool
        :param additional_info: The additional_info of this Trial.  # noqa: E501
        :type additional_info: Dict[str, str]
        :param contacts: The contacts of this Trial.  # noqa: E501
        :type contacts: List[Contact]
        :param dataset_authorship: The dataset_authorship of this Trial.  # noqa: E501
        :type dataset_authorship: TrialDatasetAuthorship
        :param end_date: The end_date of this Trial.  # noqa: E501
        :type end_date: date
        :param program_db_id: The program_db_id of this Trial.  # noqa: E501
        :type program_db_id: str
        :param program_name: The program_name of this Trial.  # noqa: E501
        :type program_name: str
        :param start_date: The start_date of this Trial.  # noqa: E501
        :type start_date: date
        :param studies: The studies of this Trial.  # noqa: E501
        :type studies: List[TrialStudies]
        :param trial_db_id: The trial_db_id of this Trial.  # noqa: E501
        :type trial_db_id: str
        :param trial_name: The trial_name of this Trial.  # noqa: E501
        :type trial_name: str
        """
        self.swagger_types = {
            'active': bool,
            'additional_info': Dict[str, str],
            'contacts': List[Contact],
            'dataset_authorship': TrialDatasetAuthorship,
            'end_date': date,
            'program_db_id': str,
            'program_name': str,
            'start_date': date,
            'studies': List[TrialStudies],
            'trial_db_id': str,
            'trial_name': str
        }

        self.attribute_map = {
            'active': 'active',
            'additional_info': 'additionalInfo',
            'contacts': 'contacts',
            'dataset_authorship': 'datasetAuthorship',
            'end_date': 'endDate',
            'program_db_id': 'programDbId',
            'program_name': 'programName',
            'start_date': 'startDate',
            'studies': 'studies',
            'trial_db_id': 'trialDbId',
            'trial_name': 'trialName'
        }

        self._active = active
        self._additional_info = additional_info
        self._contacts = contacts
        self._dataset_authorship = dataset_authorship
        self._end_date = end_date
        self._program_db_id = program_db_id
        self._program_name = program_name
        self._start_date = start_date
        self._studies = studies
        self._trial_db_id = trial_db_id
        self._trial_name = trial_name

    @classmethod
    def from_dict(cls, dikt) -> 'Trial':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The trial of this Trial.  # noqa: E501
        :rtype: Trial
        """
        return util.deserialize_model(dikt, cls)

    @property
    def active(self) -> bool:
        """Gets the active of this Trial.

        Is this trail currently active  # noqa: E501

        :return: The active of this Trial.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this Trial.

        Is this trail currently active  # noqa: E501

        :param active: The active of this Trial.
        :type active: bool
        """

        self._active = active

    @property
    def additional_info(self) -> Dict[str, str]:
        """Gets the additional_info of this Trial.

        Additional arbitrary info  # noqa: E501

        :return: The additional_info of this Trial.
        :rtype: Dict[str, str]
        """
        return self._additional_info

    @additional_info.setter
    def additional_info(self, additional_info: Dict[str, str]):
        """Sets the additional_info of this Trial.

        Additional arbitrary info  # noqa: E501

        :param additional_info: The additional_info of this Trial.
        :type additional_info: Dict[str, str]
        """

        self._additional_info = additional_info

    @property
    def contacts(self) -> List[Contact]:
        """Gets the contacts of this Trial.

        List of contact entities associated with this trial  # noqa: E501

        :return: The contacts of this Trial.
        :rtype: List[Contact]
        """
        return self._contacts

    @contacts.setter
    def contacts(self, contacts: List[Contact]):
        """Sets the contacts of this Trial.

        List of contact entities associated with this trial  # noqa: E501

        :param contacts: The contacts of this Trial.
        :type contacts: List[Contact]
        """

        self._contacts = contacts

    @property
    def dataset_authorship(self) -> TrialDatasetAuthorship:
        """Gets the dataset_authorship of this Trial.


        :return: The dataset_authorship of this Trial.
        :rtype: TrialDatasetAuthorship
        """
        return self._dataset_authorship

    @dataset_authorship.setter
    def dataset_authorship(self, dataset_authorship: TrialDatasetAuthorship):
        """Sets the dataset_authorship of this Trial.


        :param dataset_authorship: The dataset_authorship of this Trial.
        :type dataset_authorship: TrialDatasetAuthorship
        """

        self._dataset_authorship = dataset_authorship

    @property
    def end_date(self) -> date:
        """Gets the end_date of this Trial.

        The date this trial ends  # noqa: E501

        :return: The end_date of this Trial.
        :rtype: date
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: date):
        """Sets the end_date of this Trial.

        The date this trial ends  # noqa: E501

        :param end_date: The end_date of this Trial.
        :type end_date: date
        """

        self._end_date = end_date

    @property
    def program_db_id(self) -> str:
        """Gets the program_db_id of this Trial.

        A program identifier to search for  # noqa: E501

        :return: The program_db_id of this Trial.
        :rtype: str
        """
        return self._program_db_id

    @program_db_id.setter
    def program_db_id(self, program_db_id: str):
        """Sets the program_db_id of this Trial.

        A program identifier to search for  # noqa: E501

        :param program_db_id: The program_db_id of this Trial.
        :type program_db_id: str
        """

        self._program_db_id = program_db_id

    @property
    def program_name(self) -> str:
        """Gets the program_name of this Trial.

        The human readable name of a program  # noqa: E501

        :return: The program_name of this Trial.
        :rtype: str
        """
        return self._program_name

    @program_name.setter
    def program_name(self, program_name: str):
        """Sets the program_name of this Trial.

        The human readable name of a program  # noqa: E501

        :param program_name: The program_name of this Trial.
        :type program_name: str
        """

        self._program_name = program_name

    @property
    def start_date(self) -> date:
        """Gets the start_date of this Trial.

        The date this trial started  # noqa: E501

        :return: The start_date of this Trial.
        :rtype: date
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: date):
        """Sets the start_date of this Trial.

        The date this trial started  # noqa: E501

        :param start_date: The start_date of this Trial.
        :type start_date: date
        """

        self._start_date = start_date

    @property
    def studies(self) -> List[TrialStudies]:
        """Gets the studies of this Trial.

        List of studies inside this trial  # noqa: E501

        :return: The studies of this Trial.
        :rtype: List[TrialStudies]
        """
        return self._studies

    @studies.setter
    def studies(self, studies: List[TrialStudies]):
        """Sets the studies of this Trial.

        List of studies inside this trial  # noqa: E501

        :param studies: The studies of this Trial.
        :type studies: List[TrialStudies]
        """

        self._studies = studies

    @property
    def trial_db_id(self) -> str:
        """Gets the trial_db_id of this Trial.

        The ID which uniquely identifies a trial  # noqa: E501

        :return: The trial_db_id of this Trial.
        :rtype: str
        """
        return self._trial_db_id

    @trial_db_id.setter
    def trial_db_id(self, trial_db_id: str):
        """Sets the trial_db_id of this Trial.

        The ID which uniquely identifies a trial  # noqa: E501

        :param trial_db_id: The trial_db_id of this Trial.
        :type trial_db_id: str
        """

        self._trial_db_id = trial_db_id

    @property
    def trial_name(self) -> str:
        """Gets the trial_name of this Trial.

        The human readable name of a trial  # noqa: E501

        :return: The trial_name of this Trial.
        :rtype: str
        """
        return self._trial_name

    @trial_name.setter
    def trial_name(self, trial_name: str):
        """Sets the trial_name of this Trial.

        The human readable name of a trial  # noqa: E501

        :param trial_name: The trial_name of this Trial.
        :type trial_name: str
        """

        self._trial_name = trial_name
