# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bety_brapi.models.base_model_ import Model
from bety_brapi import util


class VendorSpecificationPlatformDeliverables(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, deliverable_name: str=None, description: str=None, format: str=None, name: str=None):  # noqa: E501
        """VendorSpecificationPlatformDeliverables - a model defined in Swagger

        :param deliverable_name: The deliverable_name of this VendorSpecificationPlatformDeliverables.  # noqa: E501
        :type deliverable_name: str
        :param description: The description of this VendorSpecificationPlatformDeliverables.  # noqa: E501
        :type description: str
        :param format: The format of this VendorSpecificationPlatformDeliverables.  # noqa: E501
        :type format: str
        :param name: The name of this VendorSpecificationPlatformDeliverables.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'deliverable_name': str,
            'description': str,
            'format': str,
            'name': str
        }

        self.attribute_map = {
            'deliverable_name': 'deliverableName',
            'description': 'description',
            'format': 'format',
            'name': 'name'
        }

        self._deliverable_name = deliverable_name
        self._description = description
        self._format = format
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'VendorSpecificationPlatformDeliverables':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The vendorSpecificationPlatform_deliverables of this VendorSpecificationPlatformDeliverables.  # noqa: E501
        :rtype: VendorSpecificationPlatformDeliverables
        """
        return util.deserialize_model(dikt, cls)

    @property
    def deliverable_name(self) -> str:
        """Gets the deliverable_name of this VendorSpecificationPlatformDeliverables.

        Human readable name of a vendor deliverable  # noqa: E501

        :return: The deliverable_name of this VendorSpecificationPlatformDeliverables.
        :rtype: str
        """
        return self._deliverable_name

    @deliverable_name.setter
    def deliverable_name(self, deliverable_name: str):
        """Sets the deliverable_name of this VendorSpecificationPlatformDeliverables.

        Human readable name of a vendor deliverable  # noqa: E501

        :param deliverable_name: The deliverable_name of this VendorSpecificationPlatformDeliverables.
        :type deliverable_name: str
        """

        self._deliverable_name = deliverable_name

    @property
    def description(self) -> str:
        """Gets the description of this VendorSpecificationPlatformDeliverables.


        :return: The description of this VendorSpecificationPlatformDeliverables.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this VendorSpecificationPlatformDeliverables.


        :param description: The description of this VendorSpecificationPlatformDeliverables.
        :type description: str
        """

        self._description = description

    @property
    def format(self) -> str:
        """Gets the format of this VendorSpecificationPlatformDeliverables.


        :return: The format of this VendorSpecificationPlatformDeliverables.
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format: str):
        """Sets the format of this VendorSpecificationPlatformDeliverables.


        :param format: The format of this VendorSpecificationPlatformDeliverables.
        :type format: str
        """

        self._format = format

    @property
    def name(self) -> str:
        """Gets the name of this VendorSpecificationPlatformDeliverables.

        DEPRECATED in v1.3 - Use \"deliverableName\"  # noqa: E501

        :return: The name of this VendorSpecificationPlatformDeliverables.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this VendorSpecificationPlatformDeliverables.

        DEPRECATED in v1.3 - Use \"deliverableName\"  # noqa: E501

        :param name: The name of this VendorSpecificationPlatformDeliverables.
        :type name: str
        """

        self._name = name
